import test from 'node:test';
import assert from 'node:assert/strict';

import {
  buildExportPayload,
  exportAll,
  filterCookiesForExport,
  sanitizeFilename,
  toHeaderString,
  toJsonFormat,
  toNetscapeFormat,
} from '../js/cookie-exporter.js';
import { parseCookies } from '../js/cookie-parser.js';

test('exports exact Netscape headers and seven columns', () => {
  const output = toNetscapeFormat([
    {
      domain: '.example.com',
      domainScoped: true,
      path: '/',
      secure: true,
      status: 'live',
      expirationTimestamp: 4102444800,
      name: 'sid',
      value: 'secret',
    },
  ]);

  assert.equal(
    output,
    [
      '# Netscape HTTP Cookie File',
      '# This file was generated by Zig Zag',
      '',
      '.example.com\tTRUE\t/\tTRUE\t4102444800\tsid\tsecret',
    ].join('\n'),
  );
  assert.equal(output.split('\n')[3].split('\t').length, 7);
});

test('exports session expiration as zero and host scope as false', () => {
  const output = toNetscapeFormat([
    {
      domain: 'accounts.example.com',
      domainScoped: false,
      path: '/account',
      secure: false,
      status: 'session',
      expirationTimestamp: null,
      name: 'session',
      value: 'memory-only',
    },
  ]);

  assert.equal(
    output.split('\n')[3],
    'accounts.example.com\tFALSE\t/account\tFALSE\t0\tsession\tmemory-only',
  );
});

test('sanitizes domain names for export filenames', () => {
  assert.equal(sanitizeFilename('.accounts.example.com'), 'accounts.example.com');
  assert.equal(sanitizeFilename('bad domain/segment'), 'bad_domain_segment');
});

test('keeps an unavailable path blank instead of assuming root scope', () => {
  const output = toNetscapeFormat([
    {
      domain: 'example.com',
      domainScoped: false,
      path: null,
      secure: false,
      status: 'session',
      expirationTimestamp: null,
      name: 'minimal',
      value: 'value',
    },
  ]);

  assert.equal(
    output.split('\n')[3],
    'example.com\tFALSE\t\tFALSE\t0\tminimal\tvalue',
  );
});

test('prepares the same selected cookie set for file and clipboard export', () => {
  const cookies = [
    { name: 'live', selected: true, status: 'live' },
    { name: 'session', selected: true, status: 'session' },
    { name: 'expired', selected: true, status: 'expired' },
    { name: 'not-selected', selected: false, status: 'live' },
  ];

  assert.deepEqual(
    filterCookiesForExport(cookies, {
      includeExpired: false,
      includeSession: true,
    }).map(cookie => cookie.name),
    ['live', 'session'],
  );
  assert.deepEqual(
    filterCookiesForExport(cookies, {
      includeExpired: true,
      includeSession: false,
    }).map(cookie => cookie.name),
    ['live', 'expired'],
  );
  assert.deepEqual(
    filterCookiesForExport(cookies, {
      includeExpired: false,
      includeSession: false,
    }).map(cookie => cookie.name),
    ['live'],
  );
  assert.deepEqual(filterCookiesForExport(cookies.map(cookie => ({ ...cookie, selected: false }))), []);
});

test('JSON keeps every normalized cookie field except the UI selection flag', () => {
  const raw = 'Name\tValue\tDomain\tPath\tExpires / Max-Age\tSize\tHttpOnly\tSecure\tSameSite\n' +
    'sid\tsecret\t.example.com\t/\tSession\t6\ttrue\ttrue\tLax';
  const cookie = parseCookies(raw).cookies[0];
  const { selected, ...cookieFields } = cookie;

  assert.equal(selected, true);
  assert.deepEqual(JSON.parse(toJsonFormat([cookie])), [cookieFields]);
  assert.equal(JSON.parse(toJsonFormat([cookie]))[0].value, 'secret');
});

test('Header string contains names and values in original order only', () => {
  const cookies = [
    { name: 'sid', value: 'first', domain: '.example.com', secure: true, status: 'live' },
    { name: 'sid', value: 'second', domain: 'example.com', secure: false, status: 'expired' },
    { name: 'empty', value: '', domain: 'example.com', status: 'session' },
  ];

  assert.equal(toHeaderString(cookies), 'sid=first; sid=second; empty=');
});

test('each format has a suitable filename and content type', () => {
  const cookie = { name: 'sid', value: 'secret', domain: 'example.com', status: 'session' };
  const netscape = buildExportPayload([cookie], 'netscape');
  const json = buildExportPayload([cookie], 'json');
  const header = buildExportPayload([cookie], 'header');

  assert.equal(netscape.filename, 'cookies.txt');
  assert.match(netscape.content, /# Netscape HTTP Cookie File/);
  assert.equal(json.filename, 'cookies.json');
  assert.match(json.mimeType, /^application\/json/);
  assert.equal(JSON.parse(json.content)[0].name, 'sid');
  assert.equal(header.filename, 'cookies-header.txt');
  assert.equal(header.content, 'sid=secret');
  assert.throws(() => buildExportPayload([cookie], 'unknown'), /Unsupported export format/);
});

test('all formats receive the same selected cookies after inclusion filtering', () => {
  const raw = 'Name\tValue\tDomain\tPath\tExpires / Max-Age\tSize\tHttpOnly\tSecure\tSameSite\n' +
    'live\tone\texample.com\t/\tMar 25, 2099, 01:43 PM\t3\tfalse\ttrue\tLax\n' +
    'session\ttwo\texample.com\t/\tSession\t3\tfalse\ttrue\tLax';
  const cookies = parseCookies(raw).cookies;
  const filtered = filterCookiesForExport(cookies, { includeSession: false, includeExpired: false });

  assert.deepEqual(filtered.map(cookie => cookie.name), ['live']);
  assert.match(buildExportPayload(filtered, 'netscape').content, /\tlive\tone/);
  assert.doesNotMatch(buildExportPayload(filtered, 'netscape').content, /\tsession\ttwo/);
  assert.deepEqual(JSON.parse(buildExportPayload(filtered, 'json').content).map(cookie => cookie.name), ['live']);
  assert.equal(buildExportPayload(filtered, 'header').content, 'live=one');
});

test('an empty selection does not start a Netscape download', () => {
  assert.equal(exportAll([{ name: 'sid', selected: false, status: 'live' }]), 0);
});
